apiVersion: v1
kind: Service
metadata:
  name: pingapp-svc
  labels:
    app: pingapp
spec:
  selector:
    app: pingapp
  type: NodePort
  ports:
    - port: 4567
      name: http
      targetPort: 4567
      protocol: TCP